### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pablolive1** [Eric-Canas/BetArbitrageAnalysis#1]
hola amigo, tengo este error al usar el script, ¿me pueden ayudar? si el proyecto parece maravilloso

Rugby bets have no tie possibility, thus are not ensurable
https://www.oddschecker.com/es/futbol-americano gave code 404
Futbol bets have no tie possibility, thus are not ensurable
E-Sports bets have no tie possibility, thus are not ensurable
Baloncesto bets have no tie possibility, thus are not ensurable
Tenis bets have no tie possibility, thus are not ensurable
Boxeo bets have no tie possibility, thus are not ensurable
https://www.oddschecker.com/es/tenis-mesa/tenis-de-mesa gave code 404
Ufc-Mma bets have no tie possibility, thus are not ensurable
Traceback (most recent call last):
  File "C:\Users\pablo\Desktop\BetArbitrageAnalysis-main\main.py", line 6, in <module>
    information = BetScraper().get_information(sleep_time_min=1.0, sleep_time_max=2.0)
  File "C:\Users\pablo\Desktop\BetArbitrageAnalysis-main\Scrapers\MainScraper.py", line 55, in get_information
    raise ValueError("No information found in www.oddschecker.com/es/")
ValueError: No information found in www.oddschecker.com/es/

**Comment by Eric-Canas** [comment]
Mmmmmm... Lo he probado y no me pasa, pero creo que si me pasó en
algún momento el mes pasado.
Prueba esto:
Creo, que está pasando porque recientemente la web ha puesto este aviso al
abrirla:
[image: image.png]
Prueba a abrir www.oddschecker.com/es/ antes, y aceptar el alert.

No sé realmente si viene de ahí, pero si no dime y miro si te puede estar
pasando por algún otro motivo
